
export const metadata = {
    title: 'Search Restaurant',
    description: 'Generated by create next app',
}

export default function SearchLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div>
            {children}
        </div>

    )
}
